### ISSUE TITLE
Error while executing serverless invoke local -f 

### ISSUE THREAD

**Issue by jeson114** [adieuadieu/serverless-chrome#110] opened 2018-02-06 12:20 UTC
`Error occured in serverless-plugin-chrome wrapper when trying to ensureChrome for default() handler. { flags: [ '--window-size=1280x1696', '--hide-scrollbars', '--headless' ],
  functions: [ 'requestpdf' ],
  chromePath: '/var/task/headless-chromium' } Error: Unable to start Chrome. If you have the DEBUG env variable set,there will be more in the logs.
    at /Users/jesondias/Documents/oncore/oc-print/.build/.webpack/service/src/handlers/requestPdf.js:3208:13
    at Generator.throw (<anonymous>)
    at step (/Users/jesondias/Documents/oncore/oc-print/.build/.webpack/service/src/handlers/requestPdf.js:3142:191)
    at /Users/jesondias/Documents/oncore/oc-print/.build/.webpack/service/src/handlers/requestPdf.js:3142:402
    at <anonymous>
    at process._tickDomainCallback (internal/process/ne`

Tried using serverless-offline and chrome seems to throw an error too while i attempt a POST request on one of the handlers . could this be related ?

**Comment by SidneyNemzer** [comment] 2018-09-12 01:17
Possible duplicate of #89

**Closed** 2020-10-23 19:24 UTC
