### ISSUE TITLE
Question : How would i omit the serverless-chrome plugin to be injected from some of the lambda functions in serverless.yml?

### ISSUE THREAD

**Issue by jeson114** [adieuadieu/serverless-chrome#101] opened 2018-01-07 05:56 UTC
Sorry if that's a weird question . The serverless docs aren't vey clear about this

**Comment by adieuadieu** [comment] 2018-01-07 14:04
Have a look here: https://github.com/adieuadieu/serverless-chrome/tree/master/packages/serverless-plugin#configuration

Specifically the second example code block

**Comment by jeson114** [comment] 2018-01-08 07:37
Well i tried this 
```
service: aws

provider:
  name: aws
  runtime: nodejs6.10
  stage: alpha
  region: us-east-1
  environment:
    DEBUG: "*"
    PAGE_LOAD_TIMEOUT: 20000
    LOGGING: true

plugins:
  - serverless-plugin-chrome
  - serverless-webpack

custom:
  chrome:
    flags:
      - --window-size=1280x1696 # Letter size
      - --hide-scrollbars
      - --headless
    functions:
      - requestpdf
functions:
  requestpdf:
    description: Requests a PDF print
    memorySize: 1536
    timeout: 30
    handler: src/print/requestPdf.default
    events:
      - http:
          path: pdf
          method: post
  getPdf:
    description: Retrieves a PDF
    memorySize: 1536
    timeout: 30
    handler: src/print/retrievePdf.default
    events:
      - http:
          path: pdf/{requestId}
          method: get
  getRequestStatus:
    description: Retrieves PDF print status
    memorySize: 1536
    timeout: 30
    handler: src/print/pdfStatus.default
    events:
      - http:
          path: pdf/{requestId}/status
          method: get

resources:
  Resources:
    ApiGatewayRestApi:
      Properties:
        BinaryMediaTypes:
          - "*/*"
```

But i ended up with all three lambda functions with a chrome binary injected in them . Want it just for requestPdf
![screen shot 2018-01-08 at 1 03 54 pm](https://user-images.githubusercontent.com/8187342/34662201-df356ee8-f474-11e7-911a-4b6aac77fa15.png)

**Comment by adieuadieu** [comment] 2018-01-08 20:08
Ah. This is perhaps a misunderstanding. While Chrome is only being launched for the `requestpdf` function (given your config), the Lambda functions are all being packaged into one artifact when you deploy. Serverless has a "package individually" [feature](https://serverless.com/framework/docs/providers/aws/guide/packaging/#packaging-functions-separately), but I don't think `serverless-plugin-chrome` currently supports it (see related Issue #82).

**Comment by jeson114** [comment] 2018-01-12 06:59
:( . Looks like it doesn't . Thanks for your help @adieuadieu

**Comment by adieuadieu** [comment] 2018-01-12 08:53
Closing as a duplicate of #82

**Closed by adieuadieu** 2018-01-12 08:53 UTC
