### ISSUE TITLE
Local invoking doesn't work

### ISSUE THREAD

**Issue by sebkaluzny** [adieuadieu/serverless-chrome#158] opened 2018-08-13 22:17 UTC
Hi, 
Im trying to run default script eg `serverless invoke local -f version-info` but im getting error 

> {
>     "errorMessage": "Unable to start Chrome. If you have the DEBUG env variable set,there will be more in the logs.",
>     "errorType": "Error"
> }

Node 6.14, macOS 10.13

Part of most important (i think) log

> @serverless-chrome/lambda: Error trying to spawn chrome: TypeError: Cannot read property 'toString' of undefined
 at Launcher.<anonymous> (.build/.webpack/service/src/handlers/webpack:/node_modules/chrome-launcher/dist/chrome-launcher.js:170:1)
...
> Error occured in serverless-plugin-chrome wrapper when trying to ensure Chrome for default() handler. { flags: [ '--window-size=1280,1696', '--hide-scrollbars' ],
  chromePath: '/var/task/headless-chromium' } Error: Unable to start Chrome. If you have the DEBUG env variable set,there will be more in the logs.

Also this is invalid directory `/var/task/headless-chromium` 
Thanks

**Comment by SidneyNemzer** [comment] 2018-09-12 01:17
Possible duplicate of #89

**Closed** 2020-10-23 19:25 UTC
