### ISSUE TITLE
`Error: spawn /var/task/headless-chromium ENOENT` when using webpack

### ISSUE THREAD

**Issue by dholdren** [adieuadieu/serverless-chrome#102] opened 2018-01-12 02:54 UTC
I'm using serverless-plugin-chrome and I recently switched to using webpack.
```
plugins:
  - serverless-plugin-chrome
  - serverless-webpack
```

However when I try to `invoke local` I get the following error:
```
@serverless-chrome/lambda Spawning headless shell
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
@serverless-chrome/lambda Error trying to spawn chrome: TypeError: Cannot read property 'toString' of undefined
    at Launcher.<anonymous> (/Users/dholdren/projects/test_serverless_chrome/node_modules/chrome-launcher/dist/chrome-launcher.js:170:63)
    at next (native)
    at /Users/dholdren/projects/test_serverless_chrome/node_modules/chrome-launcher/dist/chrome-launcher.js:12:71
    at __awaiter (/Users/dholdren/projects/test_serverless_chrome/node_modules/chrome-launcher/dist/chrome-launcher.js:8:12)
    at spawnPromise (/Users/dholdren/projects/test_serverless_chrome/node_modules/chrome-launcher/dist/chrome-launcher.js:155:41)
    at Launcher.<anonymous> (/Users/dholdren/projects/test_serverless_chrome/node_modules/chrome-launcher/dist/chrome-launcher.js:173:16)
    at next (native)
    at /Users/dholdren/projects/test_serverless_chrome/node_modules/chrome-launcher/dist/chrome-launcher.js:12:71
    at __awaiter (/Users/dholdren/projects/test_serverless_chrome/node_modules/chrome-launcher/dist/chrome-launcher.js:8:12)
    at Launcher.spawnProcess (/Users/dholdren/projects/test_serverless_chrome/node_modules/chrome-launcher/dist/chrome-launcher.js:153:16)
    at Launcher.<anonymous> (/Users/dholdren/projects/test_serverless_chrome/node_modules/chrome-launcher/dist/chrome-launcher.js:148:35)
    at throw (native)
    at rejected (/Users/dholdren/projects/test_serverless_chrome/node_modules/chrome-launcher/dist/chrome-launcher.js:10:65)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
@serverless-chrome/lambda stdout log:
@serverless-chrome/lambda stderr log:
Error occured in serverless-plugin-chrome wrapper when trying to ensure Chrome for handler() handler. { flags: [], chromePath: '/var/task/headless-chromium' } Error: Unable to start Chrome. If you have the DEBUG env variable set,there will be more in the logs.
    at /Users/dholdren/projects/test_serverless_chrome/node_modules/@serverless-chrome/lambda/dist/bundle.cjs.js:317:13
    at throw (native)
    at step (/Users/dholdren/projects/test_serverless_chrome/node_modules/@serverless-chrome/lambda/dist/bundle.cjs.js:258:191)
    at /Users/dholdren/projects/test_serverless_chrome/node_modules/@serverless-chrome/lambda/dist/bundle.cjs.js:258:402
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn /var/task/headless-chromium ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

I found this line which seems to be the cause of the problem, but I'm not sure what the original intent of it was:
`chromePath: this.webpack ? '/var/task/headless-chromium' : undefined,`
https://github.com/adieuadieu/serverless-chrome/blob/master/packages/serverless-plugin/src/index.js#L138

**Comment by henrikhaugboelle** [comment] 2018-01-17 15:47
I'm experiencing the same, and haven't been able to find a solution yet. Anyone with hints?

**Comment by dholdren** [comment] 2018-01-18 19:24
I'm getting this on AWS also, so I'm amending the title.

**Comment by dholdren** [comment] 2018-01-18 23:05
ok after updating the `serverless-webpack` plugin to 4.2.0, I no longer get this error on AWS. 
 The earlier version I had was missing a hook that serverless-chrome-plugin depended on.

However I do still get it locally.
I've opened a PR to fix this problem: https://github.com/adieuadieu/serverless-chrome/pull/104

**Comment by SidneyNemzer** [comment] 2018-09-12 01:17
Possible duplicate of #89, although looks like your PR will fix it. Hope it gets merged soon!

**Closed** 2020-10-23 19:24 UTC

**Comment by CWarth93** [comment] 2022-04-01 10:58
Having this issue as well...

Dependencies:
```

"dependencies": {
  "@serverless-chrome/lambda": "^1.0.0-57.2",
  "chrome-launcher": "^0.15.0",
  "dotenv": "^8.2.0",
  "moment": "^2.29.1",
  "next": "10.0.0",
  "prettier": "^2.0.2",
  "puppeteer-core": "10.1.0",
  "react": "^16.13.1",
  "react-youtube": "^7.14.0",
  "riteway": "^6.1.2"
},
"devDependencies": {
  "puppeteer": "10.1.0"
}

```
Browser start:

```

import launchChrome from '@serverless-chrome/lambda';
import { sendRequest } from './http';

const isDev = process.env.IS_LOCAL === "true";

const getBrowser = async () => {
	try { 
		const chrome = await launchChrome({
			chromeFlags: ['--headless'],			
			logLevel: 'info',
			output: 'json'
		  });
		const res = await sendRequest({ method: 'GET', url: `http://localhost:${chrome.port}/json/version` });
		const { webSocketDebuggerUrl } = res;

		let puppeteer;
		if(isDev) {
			puppeteer = require('puppeteer');
		} else {
			puppeteer = require('puppeteer-core');
		}

		const browser = await puppeteer.connect({browserWSEndpoint: webSocketDebuggerUrl});
		return browser;
	} catch (e) {
		console.log(e);
	}
};
```

Working fine on localhost

Getting: `"Error: spawn /var/task/node_modules/@serverless-chrome/lambda/dist/headless-chromium ENOENT"` on **Vercel NextJS Serverless function**

Any hint? Or is it somehow not working with vercel/nextjs?
